In [18]:
import pandas as pd
import numpy as np

In [6]:
raw_data_path = "../datasets/data_v0/"
train_data_path = "type1/"
raw_data_path += train_data_path + "data.csv"

In [12]:
raw_df = pd.read_csv(raw_data_path)
raw_df.index = pd.to_datetime(raw_df.Date_Time)
raw_df = raw_df.drop(columns=["Date_Time"])

In [43]:
cell_types = raw_df.cell_type.unique()
cell_types

array(['CS2_34', 'CS2_33'], dtype=object)

In [49]:
unique_dates_cycle1

array([datetime.date(2010, 8, 16), datetime.date(2010, 8, 17),
       datetime.date(2010, 8, 18), datetime.date(2010, 8, 19),
       datetime.date(2010, 8, 31), datetime.date(2010, 9, 7),
       datetime.date(2010, 9, 14), datetime.date(2010, 9, 24),
       datetime.date(2010, 10, 8), datetime.date(2010, 10, 18),
       datetime.date(2010, 10, 28), datetime.date(2010, 11, 1),
       datetime.date(2010, 11, 11), datetime.date(2010, 11, 22),
       datetime.date(2010, 11, 29), datetime.date(2010, 12, 21),
       datetime.date(2011, 1, 3), datetime.date(2011, 1, 12),
       datetime.date(2011, 1, 24), datetime.date(2011, 1, 31),
       datetime.date(2011, 2, 10), datetime.date(2011, 2, 18),
       datetime.date(2011, 2, 25)], dtype=object)

In [53]:
cell = cell_types[0]
cell_df = raw_df[raw_df.cell_type == cell]
unique_dates = np.unique(cell_df.index.date)
unique_dates_cycle1 = np.unique(cell_df[cell_df.Cycle_Index == 1].index.date)
cycle_inc = {}
for date1 in unique_dates:
    for i, date0 in enumerate(unique_dates_cycle1):
        if (date1 >= date0):
            inc = i
        else:
            break
    cycle_inc[date1] = inc
cycle_inc

{datetime.date(2010, 8, 16): 0,
 datetime.date(2010, 8, 17): 1,
 datetime.date(2010, 8, 18): 2,
 datetime.date(2010, 8, 19): 3,
 datetime.date(2010, 8, 20): 3,
 datetime.date(2010, 8, 21): 3,
 datetime.date(2010, 8, 22): 3,
 datetime.date(2010, 8, 23): 3,
 datetime.date(2010, 8, 24): 3,
 datetime.date(2010, 8, 25): 3,
 datetime.date(2010, 8, 26): 3,
 datetime.date(2010, 8, 27): 3,
 datetime.date(2010, 8, 28): 3,
 datetime.date(2010, 8, 29): 3,
 datetime.date(2010, 8, 31): 4,
 datetime.date(2010, 9, 1): 4,
 datetime.date(2010, 9, 2): 4,
 datetime.date(2010, 9, 3): 4,
 datetime.date(2010, 9, 4): 4,
 datetime.date(2010, 9, 5): 4,
 datetime.date(2010, 9, 6): 4,
 datetime.date(2010, 9, 7): 5,
 datetime.date(2010, 9, 8): 5,
 datetime.date(2010, 9, 14): 6,
 datetime.date(2010, 9, 15): 6,
 datetime.date(2010, 9, 16): 6,
 datetime.date(2010, 9, 17): 6,
 datetime.date(2010, 9, 18): 6,
 datetime.date(2010, 9, 19): 6,
 datetime.date(2010, 9, 20): 6,
 datetime.date(2010, 9, 21): 6,
 datetime.date(2010, 9, 22): 6,
 datetime.date(2010, 9, 23): 6,
 datetime.date(2010, 9, 24): 7,
 datetime.date(2010, 9, 25): 7,
 datetime.date(2010, 9, 26): 7,
 datetime.date(2010, 9, 27): 7,
 datetime.date(2010, 9, 28): 7,
 datetime.date(2010, 9, 29): 7,
 datetime.date(2010, 9, 30): 7,
 datetime.date(2010, 10, 1): 7,
 datetime.date(2010, 10, 8): 8,
 datetime.date(2010, 10, 9): 8,
 datetime.date(2010, 10, 10): 8,
 datetime.date(2010, 10, 11): 8,
 datetime.date(2010, 10, 12): 8,
 datetime.date(2010, 10, 13): 8,
 datetime.date(2010, 10, 14): 8,
 datetime.date(2010, 10, 15): 8,
 datetime.date(2010, 10, 16): 8,
 datetime.date(2010, 10, 17): 8,
 datetime.date(2010, 10, 18): 9,
 datetime.date(2010, 10, 19): 9,
 datetime.date(2010, 10, 20): 9,
 datetime.date(2010, 10, 21): 9,
 datetime.date(2010, 10, 22): 9,
 datetime.date(2010, 10, 23): 9,
 datetime.date(2010, 10, 24): 9,
 datetime.date(2010, 10, 25): 9,
 datetime.date(2010, 10, 26): 9,
 datetime.date(2010, 10, 27): 9,
 datetime.date(2010, 10, 28): 10,
 datetime.date(2010, 10, 29): 10,
 datetime.date(2010, 10, 30): 10,
 datetime.date(2010, 11, 1): 11,
 datetime.date(2010, 11, 2): 11,
 datetime.date(2010, 11, 3): 11,
 datetime.date(2010, 11, 4): 11,
 datetime.date(2010, 11, 5): 11,
 datetime.date(2010, 11, 6): 11,
 datetime.date(2010, 11, 7): 11,
 datetime.date(2010, 11, 8): 11,
 datetime.date(2010, 11, 9): 11,
 datetime.date(2010, 11, 10): 11,
 datetime.date(2010, 11, 11): 12,
 datetime.date(2010, 11, 12): 12,
 datetime.date(2010, 11, 13): 12,
 datetime.date(2010, 11, 14): 12,
 datetime.date(2010, 11, 15): 12,
 datetime.date(2010, 11, 16): 12,
 datetime.date(2010, 11, 17): 12,
 datetime.date(2010, 11, 18): 12,
 datetime.date(2010, 11, 19): 12,
 datetime.date(2010, 11, 20): 12,
 datetime.date(2010, 11, 22): 13,
 datetime.date(2010, 11, 23): 13,
 datetime.date(2010, 11, 24): 13,
 datetime.date(2010, 11, 29): 14,
 datetime.date(2010, 11, 30): 14,
 datetime.date(2010, 12, 1): 14,
 datetime.date(2010, 12, 2): 14,
 datetime.date(2010, 12, 3): 14,
 datetime.date(2010, 12, 4): 14,
 datetime.date(2010, 12, 5): 14,
 datetime.date(2010, 12, 6): 14,
 datetime.date(2010, 12, 7): 14,
 datetime.date(2010, 12, 8): 14,
 datetime.date(2010, 12, 21): 15,
 datetime.date(2010, 12, 22): 15,
 datetime.date(2010, 12, 23): 15,
 datetime.date(2011, 1, 3): 16,
 datetime.date(2011, 1, 4): 16,
 datetime.date(2011, 1, 5): 16,
 datetime.date(2011, 1, 6): 16,
 datetime.date(2011, 1, 7): 16,
 datetime.date(2011, 1, 8): 16,
 datetime.date(2011, 1, 9): 16,
 datetime.date(2011, 1, 10): 16,
 datetime.date(2011, 1, 11): 16,
 datetime.date(2011, 1, 12): 17,
 datetime.date(2011, 1, 13): 17,
 datetime.date(2011, 1, 14): 17,
 datetime.date(2011, 1, 15): 17,
 datetime.date(2011, 1, 16): 17,
 datetime.date(2011, 1, 17): 17,
 datetime.date(2011, 1, 18): 17,
 datetime.date(2011, 1, 19): 17,
 datetime.date(2011, 1, 20): 17,
 datetime.date(2011, 1, 24): 18,
 datetime.date(2011, 1, 25): 18,
 datetime.date(2011, 1, 26): 18,
 datetime.date(2011, 1, 27): 18,
 datetime.date(2011, 1, 31): 19,
 datetime.date(2011, 2, 1): 19,
 datetime.date(2011, 2, 2): 19,
 datetime.date(2011, 2, 3): 19,
 datetime.date(2011, 2, 4): 19,
 datetime.date(2011, 2, 5): 19,
 datetime.date(2011, 2, 6): 19,
 datetime.date(2011, 2, 7): 19,
 datetime.date(2011, 2, 8): 19,
 datetime.date(2011, 2, 10): 20,
 datetime.date(2011, 2, 11): 20,
 datetime.date(2011, 2, 12): 20,
 datetime.date(2011, 2, 13): 20,
 datetime.date(2011, 2, 14): 20,
 datetime.date(2011, 2, 15): 20,
 datetime.date(2011, 2, 16): 20,
 datetime.date(2011, 2, 17): 20,
 datetime.date(2011, 2, 18): 21,
 datetime.date(2011, 2, 19): 21,
 datetime.date(2011, 2, 20): 21,
 datetime.date(2011, 2, 21): 21,
 datetime.date(2011, 2, 22): 21,
 datetime.date(2011, 2, 23): 21,
 datetime.date(2011, 2, 24): 21,
 datetime.date(2011, 2, 25): 22,
 datetime.date(2011, 2, 26): 22,
 datetime.date(2011, 2, 27): 22,
 datetime.date(2011, 2, 28): 22,
 datetime.date(2011, 3, 1): 22,
 datetime.date(2011, 3, 2): 22,
 datetime.date(2011, 3, 3): 22,
 datetime.date(2011, 3, 4): 22}

In [45]:
cell_df.

,Cycle_Index,Current(A),Voltage(V),Charge_Capacity(Ah),Discharge_Capacity(Ah),Charge_Energy(Wh),Discharge_Energy(Wh),ACI_Phase_Angle(Deg),cell_type
Date_Time,,,,,,,,,
2010-08-16 13:44:43,1,0.0,3.303478,0.0,0.0,0.0,0.0,0,CS2_34
2010-08-16 13:44:53,1,0.0,3.303478,0.0,0.0,0.0,0.0,0,CS2_34
2010-08-16 13:45:03,1,0.0,3.303478,0.0,0.0,0.0,0.0,0,CS2_34
2010-08-16 13:45:13,1,0.0,3.303478,0.0,0.0,0.0,0.0,0,CS2_34
2010-08-16 13:45:23,1,0.0,3.303478,0.0,0.0,0.0,0.0,0,CS2_34